leinad4mind_ppr_controller:
    path: /ppr/view/{post_id}
    defaults: { _controller: leinad4mind.ppr.controller:view }
leinad4mind_pprdelete_controller:
    path: /ppr/delete/{revision_id}
    defaults: { _controller: leinad4mind.ppr.controller:delete }
leinad4mind_pprrestore_controller:
    path: /ppr/restore/{revision_id}
    defaults: { _controller: leinad4mind.ppr.controller:restore }
