imports:
    - { resource: tables.yml }
services:
    leinad4mind.ppr.controller:
        class: leinad4mind\ppr\controller\main
        arguments:
            - '@template'
            - '@dbal.conn'
            - '%leinad4mind.ppr.tables.ppr%'
            - '@auth'
            - '@user'
            - '@controller.helper'
    leinad4mind.ppr.listener:
        class: leinad4mind\ppr\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@dbal.conn'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%leinad4mind.ppr.tables.ppr%'
            - '@auth'
        tags:
            - { name: event.listener }
