imports:
    - { resource: tables.yml }
services:
    leinad4mind.post_revisions.controller:
        class: leinad4mind\post_revisions\controller\main
        arguments:
            - '@template'
            - '@dbal.conn'
            - '%leinad4mind.post_revisions.tables.post_revisions%'
            - '@auth'
            - '@user'
            - '@controller.helper'
    leinad4mind.post_revisions.listener:
        class: leinad4mind\post_revisions\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@dbal.conn'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%leinad4mind.post_revisions.tables.post_revisions%'
            - '@auth'
        tags:
            - { name: event.listener }
